sudo: required
services:
  - docker


before_install:
  - docker build -t wt3639/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true wt3639/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-328020768713"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY